/**
 * Fluxo PJ (seção 7.1). Processo é configuração (D-OB-04): mudar etapas, tarefas, donos ou
 * condições é editar este arquivo, sem tocar em telas.
 */
import type { StageDefinition, WorkflowDefinition } from "@/domain/schemas";

/** Etapas 3 a 6 precisam estar concluídas para o check-in do primeiro dia (seção 7.1). */
export const PRE_FIRST_DAY_STAGES = ["contrato", "compliance", "politicas-beneficios", "equipamentos-acessos"] as const;

export function buildStages(extra: { cltStage2?: boolean; cltStage3?: boolean } = {}): StageDefinition[] {
  return [
    {
      id: "pre-admissao",
      order: 1,
      title: "Pré-admissão",
      summary: "O RH cadastra você e prepara a sua chegada.",
      tasks: [
        {
          id: "cadastro",
          kind: "cadastro",
          title: "Cadastro no portal",
          description: "Feito pelo RH. Nasce concluído quando o caso é criado.",
          owner: "rh",
          required: true,
          unlockWhen: [],
        },
      ],
    },
    {
      id: "cadastro-documentos",
      order: 2,
      title: "Cadastro e documentos",
      summary: "Sua ficha cadastral e os documentos que o contrato precisa.",
      tasks: [
        {
          id: "ficha",
          kind: "ficha",
          title: "Preencher a ficha cadastral",
          actionLabel: "Preencher ficha",
          description: "Dados pessoais, endereço, contato de emergência e aviso de privacidade.",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 10,
          unlockWhen: [{ type: "event", event: "case.created" }],
        },
        {
          id: "documentos",
          kind: "documentos",
          title: "Enviar os documentos",
          actionLabel: "Enviar documentos",
          description: "PDF, JPG ou PNG de até 10 MB. O RH revisa cada um.",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 10,
          unlockWhen: [{ type: "event", event: "case.created" }],
        },
        ...(extra.cltStage2
          ? ([
              {
                id: "exame-agendar",
                kind: "exame_agendar",
                title: "Agendar exame admissional",
                actionLabel: "Agendar exame",
                description: "Marcar a data e a clínica do exame admissional.",
                owner: "rh",
                required: true,
                unlockWhen: [{ type: "task_done", taskId: "ficha" }],
              },
              {
                id: "exame-aso",
                kind: "exame_aso",
                title: "Enviar o ASO",
                actionLabel: "Enviar ASO",
                description: "Depois do exame, envie o atestado de saúde ocupacional.",
                owner: "new_joiner",
                required: true,
                estimatedMinutes: 3,
                unlockWhen: [{ type: "task_done", taskId: "exame-agendar" }],
              },
            ] satisfies StageDefinition["tasks"])
          : []),
        {
          id: "revisao-documentos",
          kind: "revisao_documentos",
          title: "Revisar documentos",
          actionLabel: "Revisar",
          description: "Aprovar ou rejeitar cada documento, com motivo.",
          owner: "rh",
          required: true,
          unlockWhen: [{ type: "event", event: "documents.all_submitted" }],
        },
      ],
    },
    {
      id: "contrato",
      order: 3,
      title: "Contrato",
      summary: "O RH prepara o contrato e você assina pelo portal.",
      tasks: [
        {
          id: "contrato-preparar",
          kind: "contrato_preparar",
          title: "Preparar e enviar contrato",
          actionLabel: "Enviar contrato",
          description: "Confirmar o modelo ou anexar o contrato customizado e enviar para assinatura.",
          owner: "rh",
          required: true,
          unlockWhen: [{ type: "event", event: "documents.all_approved" }],
        },
        {
          id: "contrato-assinar",
          kind: "contrato_assinar",
          title: "Revisar e assinar o contrato",
          actionLabel: "Revisar e assinar",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 5,
          unlockWhen: [{ type: "task_done", taskId: "contrato-preparar" }],
        },
        ...(extra.cltStage3
          ? ([
              {
                id: "envio-contabilidade",
                kind: "envio_contabilidade",
                title: "Enviar admissão à contabilidade",
                actionLabel: "Marcar como enviado",
                description: "Encaminhar ficha, documentos e contrato para o registro no eSocial.",
                owner: "rh",
                required: true,
                unlockWhen: [{ type: "event", event: "contract.signed" }],
              },
            ] satisfies StageDefinition["tasks"])
          : []),
      ],
    },
    {
      id: "compliance",
      order: 4,
      title: "Compliance",
      summary: "Vídeo, quiz e Código de Conduta. Não espera a aprovação dos documentos.",
      tasks: [
        {
          id: "video-compliance",
          kind: "video",
          title: "Assistir ao vídeo de compliance",
          actionLabel: "Assistir ao vídeo",
          owner: "new_joiner",
          required: true,
          // Na prática, a estimativa vem da duração do vídeo (content/compliance/video.json).
          estimatedMinutes: 8,
          unlockWhen: [{ type: "event", event: "documents.all_submitted" }],
        },
        {
          id: "quiz-compliance",
          kind: "quiz",
          title: "Responder ao quiz",
          actionLabel: "Responder ao quiz",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 5,
          unlockWhen: [{ type: "task_done", taskId: "video-compliance" }],
        },
        {
          id: "aceite-conduta",
          kind: "aceite_politica",
          title: "Aceitar o Código de Conduta",
          actionLabel: "Ler e aceitar",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 3,
          ref: "codigo-de-conduta",
          unlockWhen: [{ type: "task_done", taskId: "quiz-compliance" }],
        },
      ],
    },
    {
      id: "politicas-beneficios",
      order: 5,
      title: "Políticas e benefícios",
      summary: "As políticas do dia a dia e os seus benefícios.",
      tasks: [
        {
          id: "aceite-viagens",
          kind: "aceite_politica",
          title: "Aceitar a Política de Viagens",
          actionLabel: "Ler e aceitar",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 4,
          ref: "politica-de-viagens",
          unlockWhen: [{ type: "task_done", taskId: "quiz-compliance" }],
        },
        {
          id: "aceite-ti",
          kind: "aceite_politica",
          title: "Aceitar a Política de TI",
          actionLabel: "Ler e aceitar",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 3,
          ref: "politica-de-ti",
          unlockWhen: [{ type: "task_done", taskId: "quiz-compliance" }],
        },
        {
          id: "aceite-rotina",
          kind: "aceite_politica",
          title: "Aceitar a Rotina de Trabalho",
          actionLabel: "Ler e aceitar",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 3,
          ref: "rotina-de-trabalho",
          unlockWhen: [{ type: "task_done", taskId: "quiz-compliance" }],
        },
        {
          id: "beneficios",
          kind: "beneficios",
          title: "Conhecer os benefícios",
          actionLabel: "Ver benefícios",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 3,
          unlockWhen: [{ type: "task_done", taskId: "quiz-compliance" }],
        },
      ],
    },
    {
      id: "equipamentos-acessos",
      order: 6,
      title: "Equipamentos e acessos",
      summary: "E-mail corporativo, notebook e acessos prontos antes do primeiro dia.",
      tasks: [
        {
          id: "email-corporativo",
          kind: "email_corporativo",
          title: "Criar e-mail corporativo",
          actionLabel: "Criar e-mail",
          owner: "ti",
          required: true,
          unlockWhen: [{ type: "event", event: "contract.signed" }],
        },
        {
          id: "notebook-atribuir",
          kind: "equipamento_atribuir",
          title: "Atribuir notebook",
          actionLabel: "Atribuir notebook",
          owner: "rh",
          required: true,
          appliesWhen: "needsNotebook",
          unlockWhen: [{ type: "event", event: "contract.signed" }],
        },
        {
          id: "notebook-termo",
          kind: "termo_equipamento",
          title: "Aceitar o termo do notebook",
          actionLabel: "Ler e aceitar termo",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 2,
          appliesWhen: "needsNotebook",
          unlockWhen: [{ type: "task_done", taskId: "notebook-atribuir" }],
        },
        {
          id: "acessos",
          kind: "acessos",
          title: "Liberar acessos",
          actionLabel: "Liberar acessos",
          owner: "ti",
          required: true,
          unlockWhen: [{ type: "event", event: "contract.signed" }],
        },
      ],
    },
    {
      id: "primeiro-dia",
      order: 7,
      title: "Primeiro dia",
      summary: "Agenda, quem é quem e o check-in na data de início.",
      waitsForStartDate: true,
      tasks: [
        {
          id: "primeiro-dia-agenda",
          kind: "primeiro_dia_agenda",
          title: "Conhecer a agenda do primeiro dia",
          actionLabel: "Ver a agenda",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 3,
          unlockWhen: [{ type: "event", event: "contract.signed" }],
        },
        {
          id: "primeiro-dia-checkin",
          kind: "primeiro_dia_checkin",
          title: "Fazer check-in no primeiro dia",
          actionLabel: "Fazer check-in",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 1,
          unlockWhen: [
            { type: "date_reached", field: "startDate" },
            ...PRE_FIRST_DAY_STAGES.map((stageId) => ({ type: "stage_done" as const, stageId })),
          ],
        },
      ],
    },
    {
      id: "feedback",
      order: 8,
      title: "Feedback",
      summary: "Conte como foi. Sua resposta melhora a próxima entrada.",
      tasks: [
        {
          id: "feedback",
          kind: "feedback",
          title: "Contar como foi o onboarding",
          actionLabel: "Responder",
          owner: "new_joiner",
          required: true,
          estimatedMinutes: 2,
          unlockWhen: [{ type: "task_done", taskId: "primeiro-dia-checkin" }],
        },
      ],
    },
  ];
}

export const pjWorkflow: WorkflowDefinition = {
  id: "pj",
  regime: "PJ",
  version: 1,
  title: "Onboarding PJ",
  stages: buildStages(),
};
